# Generated by Django 2.1.7 on 2019-04-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('Start_Time', models.DateField()),
                ('End_Time', models.DateField()),
                ('Number_Of_Votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfChoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Choice', models.CharField(max_length=1000)),
                ('Election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElectionManager.Election')),
            ],
        ),
    ]
