# Generated by Django 2.1.7 on 2019-03-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionManager', '0002_auto_20190329_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Election_db',
            new_name='Election',
        ),
    ]
