# Generated by Django 2.1.7 on 2019-04-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionManager', '0003_auto_20190329_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfChoicese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Choices', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='election',
            name='List_Of_Choices',
        ),
        migrations.AddField(
            model_name='listofchoicese',
            name='foreigkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElectionManager.Election'),
        ),
    ]
